{% set name = "azure-quantum" %}
{% set version = "0.27.258160" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-quantum-{{ version }}.tar.gz
    sha256: e004845ea5602b94946c6f16faedf6c78a08b3ca2cd7622e2ab971b1e6c23d54
  - url: https://raw.githubusercontent.com/microsoft/qdk-python/release/v{{ version }}/LICENSE
    sha256: c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiofile >=3.7.2
    - aiohttp >=3.7.0
    - azure-core >=1.25.0
    - azure-identity >=1.6.0
    - azure-storage-blob >=12.13.0
    - deprecated >=1.2.12
    - msrest >=0.6.21
    - numpy >=1.21.0
    - protobuf >=3.14.0,<4.0
    - python >=3.6
  run_constrained:
    - cirq-core ==0.15.0
    - cirq-ionq ==0.15.0
    - qiskit-ionq >=0.3.3
    - qiskit-terra >=0.19.1
    - qiskit-qir >=0.1.0b12

test:
  imports:
    - azure.quantum
    - azure.quantum._authentication
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/qdk-python
  summary: Python client for Azure Quantum
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
